version: '3'

tasks:
  setup:
    cmds:
      - cp .example.env .env

  # ex: task composer -- install
  composer:
    cmds:
      - docker-compose run --rm composer {{default "--version" .CLI_ARGS}}

  pkg-update:
    cmds:
      - docker-compose run --rm composer remove takemo101/cms-tool
      - docker-compose run --rm composer require takemo101/cms-tool

  start:
    cmds:
      - docker-compose up -d cmstool-app

  shell:
    cmds:
      - docker-compose exec cmstool-app bash

  stop:
    cmds:
      - docker-compose stop cmstool-app

  # ex: task serve PORT=8000 ROOT=./public/index.php
  serve:
    cmds:
      - php -S {{default "localhost" .HOST}}:{{default "8080" .PORT}} {{default "./public/index.php" .ROOT}}

  ngrok-start:
    cmds:
      - docker-compose up -d ngrok

  ngrok-stop:
    cmds:
      - docker-compose stop ngrok
